// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn5sZLWIcyPmTOWxaoVhpE145MrD2Lac4',
    appId: '1:630650359824:web:50deebba3bf5cb7143ba95',
    messagingSenderId: '630650359824',
    projectId: 'mychatapp-6af09',
    authDomain: 'mychatapp-6af09.firebaseapp.com',
    storageBucket: 'mychatapp-6af09.appspot.com',
    measurementId: 'G-T446SJ9FH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-FPQdxfXEqbO21EFG-9IhUu5AsTGOqw',
    appId: '1:630650359824:android:b6ca4e1d81e2f9cb43ba95',
    messagingSenderId: '630650359824',
    projectId: 'mychatapp-6af09',
    storageBucket: 'mychatapp-6af09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6bUsBwTLbDVh7lEjHt_wlc_EmjO6gRI',
    appId: '1:630650359824:ios:e2e44ea5d27ce69d43ba95',
    messagingSenderId: '630650359824',
    projectId: 'mychatapp-6af09',
    storageBucket: 'mychatapp-6af09.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
